### ISSUE TITLE
Build failed v0.2.4

### ISSUE THREAD

**Issue by Rockvole** [VolodymyrLykhonis/flutter_billing#13]
I upgraded my flutter today and started getting this error with your package.

    /home/david/.pub-cache/hosted/pub.dartlang.org/flutter_billing-
    0.2.4/android/src/main/java/com/lykhonis/flutterbilling/BillingPlugin.java:163: error: ';' expected
        }
         ^
    1 error

    FAILURE: Build failed with an exception.

Also, if I download your project and load into android studio I get another error :

    The current Dart SDK version is 2.1.0-dev.3.0.flutter-760a9690c2.

    Because flutter_billing_example depends on synchronized >=1.0.0 <1.5.1 which requires SDK version >=1.9.1 <2.0.0, version solving failed.
    pub get failed (1)

**Comment by Rockvole** [comment]
[✓] Flutter (Channel master, v0.7.6-pre.11, on Linux, locale en_CA.UTF-8)
    • Flutter version 0.7.6-pre.11 at /work/installs/flutter
    • Framework revision 251e82d211 (32 minutes ago), 2018-08-31 13:31:56 -0700
    • Engine revision f612a761c2
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/david/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/david/Android/Sdk
    • Java binary at: /work/installs/android-studio-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /work/installs/android-studio-3.0
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /work/installs/idea-IC-181.4445.78
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 181.4892.1
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)

! Doctor found issues in 1 category.

**Comment by lykhonis** [comment]
Will be fixed in v0.2.5
