### ISSUE TITLE
Exception when calling getProducts

### ISSUE THREAD

**Issue by NotThatBowser** [VolodymyrLykhonis/flutter_billing#14]
When calling getProducts there is an exception:

`type 'String' is not a subtype of type 'BillingProductType'`

This looks like it makes sense as it's reading a json string but expecting an enum (flutter_billing.dart, line 121).

**Comment by lykhonis** [comment]
Do you still see the issue? What version of plugin do you use?

**Comment by NotThatBowser** [comment]
Yeah.  Version is 0.2.5 (latest) and using Android platform.

For now I've changed my local copy so line 121 always assigns 'BillingProductType.INAPP' since I'm not using subscriptions.  The same issue occurs on line 158 too.

It looks like it's taking in a string from the 'product' json response and assigning it to BillingProduct's 'type' field ( 'BillingProductType' enum) without conversion.  The compiler isn't complaining because .fromIterable treats the input as dynamic so it doesn't know 'product' is a list of strings.

I'm not sure the best way to convert String to enum in dart, but this seems to work:
`BillingProductType.values.firstWhere((e) => e.toString == product['type'])`

**Comment by lykhonis** [comment]
You can revert to v0.2.3. Subscription commit introduced couple regressions and bugs I will need to address. I am working on couple more things at the moment, but will use billing plugin soon. Once I get to it I will upgrade it to v0.2.6 with fixes.

**Comment by lykhonis** [comment]
Pushed a commit https://github.com/VolodymyrLykhonis/flutter_billing/commit/cbda712c91ba747cd792623efcfe749f7a27fd00 but did not run any tests yet. If you like, you can check out this plugin locally and link it to your project.

**Comment by lykhonis** [comment]
Resolved in v0.3.0

**Comment by AlexBacich** [comment]
Thank you for quick workaround. It works.
