### ISSUE TITLE
Restore purchase option

### ISSUE THREAD

**Issue by BPHvZ** [VolodymyrLykhonis/flutter_billing#2]
Restoring a purchase would be very helpful. Thank you for the easy to use plug-in.

**Comment by lykhonis** [comment]
You can use `getPurchases` to request what identifiers (skus) have already been purchased by the customer.  [Billing.getPurchases()](https://github.com/VolodymyrLykhonis/flutter_billing/blob/master/lib/flutter_billing.dart#L129)
