### ISSUE TITLE
getPurchases seems to not be returning anything.

### ISSUE THREAD

**Issue by ItsCalebJones** [VolodymyrLykhonis/flutter_billing#4]
I've stepped through the code and I can see it making the call to getPurchases through invokeMethod in platform_channel.dart however I never see a result come back for it. 

I am using the iOS Simulator on MacOS (obviously) to test this.

Any tips would be awesome.

**Comment by lykhonis** [comment]
Have you setup non Apple Id account to test in app purchases on iOS? There is specific procedure you would need to follow to get that going.

**Comment by ItsCalebJones** [comment]
Nah - i'll look into it - thanks!
