### ISSUE TITLE
Support IAP in kindle devices

### ISSUE THREAD

**Issue by Rockvole** [VolodymyrLykhonis/flutter_billing#8]
Hi,
Do you plan to add support for Amazon Kindle devices ?

You can see more details here :
https://github.com/JackAppDev/flutter_iap/issues/11

**Comment by satya1395** [comment]
+1

**Comment by Rockvole** [comment]
I asked amazon :
https://forums.developer.amazon.com/questions/180254/support-flutter-iap-for-kindle-devices.html

**Comment by Rockvole** [comment]
IAP for Amazon Kindle has been added to :
https://github.com/dooboolab/flutter_inapp_purchase
